[tool.poetry]
name = "orsa-mac"
version = "0.1.0"
description = ""
authors = ["Luke Miller <luke@cegorach.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.13"
scipy = "^1.15.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
